## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "alexander" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "alexander", "doc" )[1]![1], "alexander.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "alexander" );
QUIT;
